name: map_validation
description: O pacote Map Validation fornece uma maneira flexível e extensível de validar dados de um `Map` em Dart, inspirado no Joi.js. Permite criar esquemas de validação com suporte a tipos variados, mensagens de erro personalizadas e internacionalização.
version: 1.0.0
repository: https://github.com/fermaiasoares/map_validation

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  faker: ^2.1.0
  lints: ^4.0.0
  test: ^1.24.0
